name: lovequest
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+26

environment:
  sdk: '>=3.0.0 <4.0.0' # Расширим диапазон для совместимости

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Добавь эту строку
    sdk: flutter         # и эту


  # --- UI и Утилиты ---
  cupertino_icons: ^1.0.2
  go_router: ^16.2.4
  equatable: ^2.0.5
  path_provider: ^2.1.5
  uuid: ^4.3.3
  http: ^1.2.1
  intl: ^0.20.2
  vector_math: ^2.1.4 # ИСПРАВЛЕНО на стабильную версию
  percent_indicator: ^4.2.3
  flutter_markdown: ^0.6.14



  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.3.1
  flutter_card_swiper: ^7.0.0

  # --- Управление состоянием ---
  flutter_bloc: ^9.1.1
  logger: ^2.0.1

  # --- Firebase (КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ) ---
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^6.2.1

  # --- Анимации и "ВАУ-эффект" ---
  flutter_animate: ^4.5.0 # Обновлено до последней версии
  simple_animations: ^5.0.2
  animate_gradient: ^0.0.2+1
  flutter_staggered_grid_view: ^0.7.0

  # --- Сенсоры и Уведомления ---
  sensors_plus: ^7.0.0
  flutter_local_notifications: ^19.4.2

  onesignal_flutter: ^5.1.0 # Последняя версия


  # --- Шифрование и утилиты ---

  crypto: ^3.0.3
  html: ^0.15.4
  enough_convert: ^1.4.0
  async: ^2.11.0
  share_plus: ^12.0.0
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  location: ^8.0.1
  geoflutterfire_plus: ^0.0.32 # ОБНОВЛЕНО. ВНИМАНИЕ: могут быть breaking changes!
  cryptography: ^2.7.0
  flutter_parsed_text: ^2.2.1
  file_picker: ^10.0.0
  screenshot: ^3.0.0


  # --- Платформо-зависимые ---

  badges: ^3.1.2
  blurrycontainer: ^2.1.0
  just_audio: ^0.10.5
  # audioplayers: ^5.2.1 # Рекомендую закомментировать, если не используется активно
  confetti: ^0.8.0
  app_links: ^6.1.1
  flutter_secure_storage: ^9.2.4
  audioplayers: ^6.5.1
  collection: ^1.18.0
  timeago: ^3.6.1
  photo_view: ^0.15.0
  universal_io: ^2.2.2 # Или последняя версия

  language_detector: ^1.0.1
  webview_flutter:

  window_manager: ^0.3.8
  qr_flutter: ^4.1.0
  cloudinary_public: ^0.23.1




  # --- Астрология ---
  sweph:
    path: ./packages/sweph
  url_launcher: ^6.2.10
  flutter_svg: ^2.1.7
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.12

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/tarot/
    - assets/ephe/seas_18.se1
    - assets/ephe/semo_18.se1
    - assets/ephe/semo_24.se1
    - assets/ephe/sepl_18.se1
    - assets/ephe/sepl_24.se1
    - assets/ephe/seplm18.se1
    - assets/images/
    - assets/images/zodiac/
    - assets/sounds/
    - assets/images/palm_guide.svg
    - assets/images/stores/
    - assets/docs/ # <-- Добавьте эту строку



    # Мы уже включили всю папку assets/images/, 
    # поэтому отдельно указывать assets/images/zodiac/ не нужно.

# ... (конец файла pubspec.yaml)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Иконка с фоном для iOS
  min_sdk_android: 21
  adaptive_icon_background: "#121212" # Цвет фона (или путь к картинке)
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" # Иконка без фона